---
- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Start Sonar
  systemd:
    name: sonar
    state: started
    enabled: yes

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

